HopestoneApp/Models/ErrorViewModel.cs
namespace HopestoneApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HopestoneApp/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HopestoneApp.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Icon { get; set; }

        [Required]
        public string Image { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public DateTime Created { get; set; }

        [Required]
        public DateTime Updated { get; set; }

        [Display(Name = "Item Status")]
        [Required]
        public bool IsActive { get; set; }
    }
}

HopestoneApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace HopestoneApp.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HopestoneApp/Controllers/HomeController.cs
using HopestoneApp.Data;
using HopestoneApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;

namespace HopestoneApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly AppDbContext _appDb;

        public HomeController(ILogger<HomeController> logger, AppDbContext db)
        {
            _logger = logger;
            _appDb = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Product> objList = _appDb.Products;
            return View(objList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HopestoneApp/Controllers/ProductController.cs
using HopestoneApp.Data;
using HopestoneApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace HopestoneApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _appDb;

        public ProductController(AppDbContext db)
        {
            _appDb = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Product> objList = _appDb.Products;
            return View(objList);
        }

        //Get-Create
        public IActionResult Create()
        {
            return View();
        }

        //Post-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {
            if (ModelState.IsValid)
            {
                _appDb.Products.Add(obj);
                _appDb.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(obj);
            }
        }

        //Get-Update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _appDb.Products.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                return View(obj);
            }
        }

        //Post-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Product obj)
        {
            _appDb.Products.Update(obj);
            _appDb.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get-Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _appDb.Products.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                return View(obj);
            }
        }
    }
}

HopestoneApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Administrator | Hopestone Construction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Administrator Page</h4>
<a class="m-5 py-5" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
<a class="m-5 py-5" asp-area="" asp-controller="Product" asp-action="Index">Product Page</a>

HopestoneApp/Views/Product/Create.cshtml
@model HopestoneApp.Models.Product
@{
    ViewData["Title"] = "Add New | Product and Services - Hopestone Construction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--
    TO DO:
        INCLUDE BATCH UPLOAD OF DATA
-->

<div class="container-fluid container-lg py-5">

    <h4 class="text-aqua">Add New Product or Service</h4>

    <form id="creation" method="post" asp-action="Create" class="needs-validation border p-3 rounded-3" novalidate>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="mb-3">
            <div class="form-floating mb-1">
                <input type="text" class="form-control" id="Title" aria-describedby="titleHelp"
                       placeholder="..." required data-bs-toggle="tooltip"
                       data-bs-placement="top" title="Please provide meaningful title."
                       asp-for="Title">
                <label asp-for="Title" class="form-label">Title</label>
            </div>
            <div id="titleHelp" class="form-text mb-2">Refrain from using special characters.</div>
        </div>

        <div class="row g-3">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Icon" placeholder="..." required
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Please specify exact file name with ext like .jpg .png .ico .svg"
                           asp-for="Icon">
                    <label asp-for="Icon">Icon Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Image" placeholder="..." required
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Please specify exact file name with ext like .jpg .png .ico .svg"
                           asp-for="Image">
                    <label asp-for="Image">Image Name</label>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="form-floating mb-1">
                <textarea class="form-control" placeholder="..." id="Description"
                          aria-describedby="descriptionHelp"
                          required minlength="10"
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Brief description of the service or product."
                          asp-for="Description"></textarea>
                <label asp-for="Description">Description</label>
            </div>
            <div id="descriptionHelp" class="form-text mb-2">Please provide a brief details of the service or product.</div>
        </div>

        <div class="row g-3">
            <div class="col-md-4">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Created" placeholder="..." required readonly
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Date of creation."
                           value="@DateTime.Now"
                           asp-for="Created">
                    <label asp-for="Created">Date Created</label>
                </div>
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Updated" placeholder="..." required readonly
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Date last updated."
                           value="@DateTime.Now"
                           asp-for="Updated">
                    <label asp-for="Updated">Date Updated</label>
                </div>
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <div class="form-floating">
                    <select class="form-select" id="IsActive" aria-label="Product Status"
                            asp-for="IsActive">
                        <option selected hidden>--Please select status--</option>
                        <option value="true">Active</option>
                        <option value="false">Inactive</option>
                    </select>
                    <label asp-for="IsActive">Item Status</label>
                </div>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
        </div>
        <div class="row g-3">
            <div class="col text-center">
                <button type="submit" class="btn btn-primary w-md-25"><i class="far fa-save"></i> Save</button>
            </div>
            <div class="col text-center">
                <a asp-action="Index" class="btn btn-danger w-md-25" data-bs-dismiss="creation"><i class="fas fa-sign-out-alt"></i> Back</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HopestoneApp/Views/Product/Index.cshtml
@model IEnumerable<HopestoneApp.Models.Product>
@{
    ViewData["Title"] = "Products and Services List | Hopestone Construction Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid bg-white-80" style="height: 100vh">

    <h4>Product Page</h4>
    <a asp-area="" asp-controller="Home" asp-action="Index" class="m-5 py-5">Home</a>
    <a asp-area="" asp-controller="Admin" asp-action="Index" class="m-5 py-5">Admin</a>

    <div class="container-fluid container-lg p-3 my-2 rounded" style="height: 520px; overflow-y:auto; border: 1px solid var(--clr-gray-60); position: relative">
        <div class="d-sm-none alert alert-warning alert-dismissible fade show" role="alert">
            <strong>For Mobile Users!</strong> Please use landscape mode to view more details.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div class="row pt-4 d-flex justify-content-around align-content-center" style="position: sticky;">
            <div class="col-6">
                <h2 class="text-primary display-6 fw-bold">
                    List of Products and Services
                </h2>
            </div>
            <div class="col-6 text-md-center text-end align-self-center">
                <a asp-action="Create" class="btn btn-primary text-light">
                    <i class="fas fa-plus"></i>
                    Add New
                </a>
            </div>
        </div>
        <br />
        <div class="table-container w-100">

            @if (Model.Count() > 0)
            {
                <table class="table table-hover table-bordered border-white table-condensed table-responsive">
                    <thead>
                        <tr class="bg-aqua text-white">
                            <th>Title</th>
                            <th>Description</th>
                            <th>Icon URL</th>
                            <th>Image URL</th>
                            <th>Date Creation</th>
                            <th>Date Updated</th>
                            <th>Status (Active)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var product in Model)
                        {
                            <tr>
                                <td class="fw-bold" style="width:12.5%; background-color: var(--clr-gray-60);">@product.Title</td>
                                <td style="width:12.5%">@product.Description</td>
                                <td style="width:12.5%">@product.Icon</td>
                                <td style="width:12.5%">@product.Image</td>
                                <td style="width:12.5%">@product.Created</td>
                                <td style="width:12.5%">@product.Updated</td>
                                <td style="width:12.5%">@product.IsActive</td>
                                <td class="w-100 btn-group" role="group">
                                    <a class="btn btn-outline-info mx-1" asp-action="Update" asp-route-Id="@product.Id"
                                       data-bs-toggle="tooltip" data-bs-placement="top"
                                       title="Update Item"><i class="far fa-edit"></i></a>
                                    <a class="btn btn-outline-danger mx-1" asp-action="Delete" asp-route-Id="@product.Id"
                                       data-bs-toggle="tooltip" data-bs-placement="top"
                                       title="Delete"><i class="fas fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No Expense to display.</p>
            }
        </div>
    </div>
</div>

HopestoneApp/Views/Product/Update.cshtml
@model HopestoneApp.Models.Product

@{
    ViewData["Title"] = "Update | Product and Services - Hopestone Construction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--
    Note:
-->

<div class="container-fluid container-lg py-5">

    <h4 class="text-aqua">Add New Product or Service</h4>

    <form id="updateItem" method="post" asp-action="Update" class="needs-validation border p-3 rounded-3" novalidate>
        <div asp-validation-summary="ModelOnly"></div>
        <input asp-for="Id" hidden />
        <div class="mb-3">
            <div class="form-floating mb-1">
                <input type="text" class="form-control" id="Title" aria-describedby="titleHelp"
                       placeholder="..." required data-bs-toggle="tooltip"
                       data-bs-placement="top" title="Please provide meaningful title."
                       asp-for="Title">
                <label asp-for="Title" class="form-label">Title</label>
            </div>
            <div id="titleHelp" class="form-text mb-2">Refrain from using special characters.</div>
        </div>

        <div class="row g-3">
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Icon" placeholder="..." required
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Please specify exact file name with ext like .jpg .png .ico .svg"
                           asp-for="Icon">
                    <label asp-for="Icon">Icon Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Image" placeholder="..." required
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Please specify exact file name with ext like .jpg .png .ico .svg"
                           asp-for="Image">
                    <label asp-for="Image">Image Name</label>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="form-floating mb-1">
                <textarea class="form-control" placeholder="..." id="Description"
                          aria-describedby="descriptionHelp"
                          required minlength="10"
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Brief description of the service or product."
                          asp-for="Description"></textarea>
                <label asp-for="Description">Description</label>
            </div>
            <div id="descriptionHelp" class="form-text mb-2">Please provide a brief details of the service or product.</div>
        </div>

        <div class="row g-3">
            <div class="col-md-4">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Created" placeholder="..." required readonly
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Date of creation."
                           asp-for="Created">
                    <label asp-for="Created">Date Created</label>
                </div>
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="Updated" placeholder="..." required readonly
                           data-bs-toggle="tooltip" data-bs-placement="top"
                           title="Date last updated."
                           value="@DateTime.Now"
                           asp-for="Updated">
                    <label asp-for="Updated">Date Updated</label>
                </div>
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <div class="form-floating">
                    <select class="form-select" id="IsActive" aria-label="Product Status"
                            asp-for="IsActive">
                        <option selected hidden>--Please select status--</option>
                        <option value="true">Active</option>
                        <option value="false">Inactive</option>
                    </select>
                    <label asp-for="IsActive">Item Status</label>
                </div>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
        </div>
        <div class="row g-3">
            <div class="col text-center">
                <button type="submit" class="btn btn-success w-md-25"><i class="far fa-save"></i> Save</button>
            </div>
            <div class="col text-center">
                <a asp-action="Index" class="btn btn-danger w-md-25" data-bs-dismiss="updateItem"><i class="fas fa-sign-out-alt"></i> Back</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HopestoneApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/dist/css/bootstrap.css" media="all" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container-fluid p-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true" type="application/javascript"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>